# Use Java 17 as the base image
FROM openjdk:17-jre-slim

# Set the working directory inside the container
WORKDIR /usr/app

# Copy the JAR file from the target folder to the container
COPY target/spring-petclinic-3.3.0-SNAPSHOT.jar /usr/app/app.jar

# Run the application
CMD ["java", "-jar", "/usr/app/app.jar"]


